@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor LOGIC_COLOR_T4
skinparam classBackgroundColor LOGIC_COLOR

Class "{abstract}\nCommand" as Command
Class XYZCommand

package "Parser classes"{
Class "<<interface>>\nParser" as Parser
Class StudentBookParser
Class XYZCommandParser
Class CliFlags
Class ParserUtil
Class FlagArgumentMap
Class FlagTokenizer
Class CommandTokenizer
Class Flag
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> StudentBookParser

StudentBookParser .down.> XYZCommandParser: <<create>>

XYZCommandParser ..> XYZCommand : <<create>>
StudentBookParser ..> Command : <<use>>
XYZCommandParser .up.|> Parser
XYZCommandParser ..> FlagArgumentMap
XYZCommandParser ..> FlagTokenizer
FlagTokenizer .left.> FlagArgumentMap
FlagTokenizer ..> CommandTokenizer
XYZCommandParser ..> CliFlags
CliFlags ..> Flag
XYZCommandParser ..> ParserUtil
FlagArgumentMap .down.> Flag
FlagTokenizer .down.> Flag
XYZCommand -up-|> Command
@enduml
